# Generated by Django 3.1.13 on 2021-11-03 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(db_column='orderDate')),
                ('cardNumber', models.IntegerField(db_column='cardNumber')),
                ('cardExpiry', models.CharField(db_column='cardExpiry', max_length=10)),
                ('shippingStreetAddress', models.CharField(db_column='shippingStreetAddress', max_length=500)),
                ('shippingCity', models.CharField(db_column='shippingCity', max_length=100)),
                ('shippingState', models.CharField(db_column='shippingState', max_length=100)),
                ('shippingZip', models.CharField(db_column='shippingZip', max_length=20)),
                ('shippingCountry', models.CharField(db_column='shippingCountry', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFurbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.furby')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.order')),
            ],
        ),
    ]
