# Generated by Django 3.1.13 on 2021-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_order_orderfurbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isConfirmed',
            field=models.IntegerField(db_column='isConfirmed', null=True),
        ),
    ]
