# Generated by Django 3.1.13 on 2021-11-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211103_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lastLoginDate',
            field=models.DateTimeField(db_column='lastLoginDate', null=True),
        ),
    ]
