# Generated by Django 3.1.7 on 2021-11-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211103_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation',
            field=models.CharField(db_column='confirmation', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='isConfirmed',
            field=models.BooleanField(db_column='isConfirmed', default=False),
        ),
    ]
